/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessProfessionnalPartyProfessionnal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BusinessProfessionnalParty
 */
public class BusinessProfessionnalPartyTest {
    private final BusinessProfessionnalParty model = new BusinessProfessionnalParty();

    /**
     * Model tests for BusinessProfessionnalParty
     */
    @Test
    public void testBusinessProfessionnalParty() {
        // TODO: test BusinessProfessionnalParty
    }

    /**
     * Test the property 'professionnal'
     */
    @Test
    public void professionnalTest() {
        // TODO: test professionnal
    }

}
