/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessAddress;
import org.openapitools.client.model.BusinessPerson;
import org.openapitools.client.model.BusinessProfessionnalParty;
import org.openapitools.client.model.BusinessSubscriberEInvoicing;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BusinessSubscriber
 */
public class BusinessSubscriberTest {
    private final BusinessSubscriber model = new BusinessSubscriber();

    /**
     * Model tests for BusinessSubscriber
     */
    @Test
    public void testBusinessSubscriber() {
        // TODO: test BusinessSubscriber
    }

    /**
     * Test the property 'subscriberRef'
     */
    @Test
    public void subscriberRefTest() {
        // TODO: test subscriberRef
    }

    /**
     * Test the property 'subscriberType'
     */
    @Test
    public void subscriberTypeTest() {
        // TODO: test subscriberType
    }

    /**
     * Test the property 'party'
     */
    @Test
    public void partyTest() {
        // TODO: test party
    }

    /**
     * Test the property 'eInvoicing'
     */
    @Test
    public void eInvoicingTest() {
        // TODO: test eInvoicing
    }

    /**
     * Test the property 'contactPerson'
     */
    @Test
    public void contactPersonTest() {
        // TODO: test contactPerson
    }

    /**
     * Test the property 'contactAddress'
     */
    @Test
    public void contactAddressTest() {
        // TODO: test contactAddress
    }

    /**
     * Test the property 'billingAddress'
     */
    @Test
    public void billingAddressTest() {
        // TODO: test billingAddress
    }

}
