/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for QueryMetadataResponse
 */
public class QueryMetadataResponseTest {
    private final QueryMetadataResponse model = new QueryMetadataResponse();

    /**
     * Model tests for QueryMetadataResponse
     */
    @Test
    public void testQueryMetadataResponse() {
        // TODO: test QueryMetadataResponse
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'countItems'
     */
    @Test
    public void countItemsTest() {
        // TODO: test countItems
    }

    /**
     * Test the property 'totalItems'
     */
    @Test
    public void totalItemsTest() {
        // TODO: test totalItems
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    public void totalPagesTest() {
        // TODO: test totalPages
    }

}
