/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ContractResponse;
import org.openapitools.client.model.ContractsResponse;
import org.openapitools.client.model.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchReadApi
 */
@Ignore
public class SearchReadApiTest {

    private final SearchReadApi api = new SearchReadApi();

    
    /**
     * Read a Contract
     *
     * Get an existing Contract
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContractTest() throws ApiException {
        String contractRef = null;
        ContractResponse response = api.getContract(contractRef);

        // TODO: test validations
    }
    
    /**
     * Search Contracts
     *
     * Multi-criteria search for contracts. The result is a list (maybe empty) of contracts
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchContractsTest() throws ApiException {
        String subscriberRef = null;
        String contractStatus = null;
        Integer limit = null;
        Integer offset = null;
        ContractsResponse response = api.searchContracts(subscriberRef, contractStatus, limit, offset);

        // TODO: test validations
    }
    
}
