/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessProfessionnalPartyProfessionnal;

/**
 * Describes professionnal organisation
 */
@ApiModel(description = "Describes professionnal organisation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:19:57.320415+02:00[Europe/Paris]")
public class BusinessProfessionnalParty {
  public static final String SERIALIZED_NAME_PROFESSIONNAL = "professionnal";
  @SerializedName(SERIALIZED_NAME_PROFESSIONNAL)
  private BusinessProfessionnalPartyProfessionnal professionnal;


  public BusinessProfessionnalParty professionnal(BusinessProfessionnalPartyProfessionnal professionnal) {
    
    this.professionnal = professionnal;
    return this;
  }

   /**
   * Get professionnal
   * @return professionnal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessProfessionnalPartyProfessionnal getProfessionnal() {
    return professionnal;
  }


  public void setProfessionnal(BusinessProfessionnalPartyProfessionnal professionnal) {
    this.professionnal = professionnal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessProfessionnalParty businessProfessionnalParty = (BusinessProfessionnalParty) o;
    return Objects.equals(this.professionnal, businessProfessionnalParty.professionnal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(professionnal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessProfessionnalParty {\n");
    sb.append("    professionnal: ").append(toIndentedString(professionnal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

