/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BusinessAddress
 */
public class BusinessAddressTest {
    private final BusinessAddress model = new BusinessAddress();

    /**
     * Model tests for BusinessAddress
     */
    @Test
    public void testBusinessAddress() {
        // TODO: test BusinessAddress
    }

    /**
     * Test the property 'line1'
     */
    @Test
    public void line1Test() {
        // TODO: test line1
    }

    /**
     * Test the property 'line2'
     */
    @Test
    public void line2Test() {
        // TODO: test line2
    }

    /**
     * Test the property 'line3'
     */
    @Test
    public void line3Test() {
        // TODO: test line3
    }

    /**
     * Test the property 'line4'
     */
    @Test
    public void line4Test() {
        // TODO: test line4
    }

    /**
     * Test the property 'line5'
     */
    @Test
    public void line5Test() {
        // TODO: test line5
    }

    /**
     * Test the property 'locality'
     */
    @Test
    public void localityTest() {
        // TODO: test locality
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'countryName'
     */
    @Test
    public void countryNameTest() {
        // TODO: test countryName
    }

}
