/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BusinessProfessionnalPartyProfessionnal
 */
public class BusinessProfessionnalPartyProfessionnalTest {
    private final BusinessProfessionnalPartyProfessionnal model = new BusinessProfessionnalPartyProfessionnal();

    /**
     * Model tests for BusinessProfessionnalPartyProfessionnal
     */
    @Test
    public void testBusinessProfessionnalPartyProfessionnal() {
        // TODO: test BusinessProfessionnalPartyProfessionnal
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'customerRef'
     */
    @Test
    public void customerRefTest() {
        // TODO: test customerRef
    }

}
