/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessAddress;
import org.openapitools.client.model.BusinessPerson;
import org.openapitools.client.model.BusinessSellerEFacturation;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BusinessSeller
 */
public class BusinessSellerTest {
    private final BusinessSeller model = new BusinessSeller();

    /**
     * Model tests for BusinessSeller
     */
    @Test
    public void testBusinessSeller() {
        // TODO: test BusinessSeller
    }

    /**
     * Test the property 'sellerRef'
     */
    @Test
    public void sellerRefTest() {
        // TODO: test sellerRef
    }

    /**
     * Test the property 'eFacturation'
     */
    @Test
    public void eFacturationTest() {
        // TODO: test eFacturation
    }

    /**
     * Test the property 'contactPerson'
     */
    @Test
    public void contactPersonTest() {
        // TODO: test contactPerson
    }

    /**
     * Test the property 'contactAddress'
     */
    @Test
    public void contactAddressTest() {
        // TODO: test contactAddress
    }

}
