/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BusinessSubscriberEInvoicing
 */
public class BusinessSubscriberEInvoicingTest {
    private final BusinessSubscriberEInvoicing model = new BusinessSubscriberEInvoicing();

    /**
     * Model tests for BusinessSubscriberEInvoicing
     */
    @Test
    public void testBusinessSubscriberEInvoicing() {
        // TODO: test BusinessSubscriberEInvoicing
    }

    /**
     * Test the property 'siren'
     */
    @Test
    public void sirenTest() {
        // TODO: test siren
    }

    /**
     * Test the property 'tvaIntracommunautaire'
     */
    @Test
    public void tvaIntracommunautaireTest() {
        // TODO: test tvaIntracommunautaire
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

}
