/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessAddress;
import org.openapitools.client.model.BusinessBuyerEInvoicing;
import org.openapitools.client.model.BusinessPerson;
import org.openapitools.client.model.BusinessProfessionnalParty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BusinessBuyer
 */
public class BusinessBuyerTest {
    private final BusinessBuyer model = new BusinessBuyer();

    /**
     * Model tests for BusinessBuyer
     */
    @Test
    public void testBusinessBuyer() {
        // TODO: test BusinessBuyer
    }

    /**
     * Test the property 'buyerRef'
     */
    @Test
    public void buyerRefTest() {
        // TODO: test buyerRef
    }

    /**
     * Test the property 'buyerType'
     */
    @Test
    public void buyerTypeTest() {
        // TODO: test buyerType
    }

    /**
     * Test the property 'party'
     */
    @Test
    public void partyTest() {
        // TODO: test party
    }

    /**
     * Test the property 'eInvoicing'
     */
    @Test
    public void eInvoicingTest() {
        // TODO: test eInvoicing
    }

    /**
     * Test the property 'contactPerson'
     */
    @Test
    public void contactPersonTest() {
        // TODO: test contactPerson
    }

    /**
     * Test the property 'contactAddress'
     */
    @Test
    public void contactAddressTest() {
        // TODO: test contactAddress
    }

    /**
     * Test the property 'billingAddress'
     */
    @Test
    public void billingAddressTest() {
        // TODO: test billingAddress
    }

}
