/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessDistributor;
import org.openapitools.client.model.BusinessSubscriber;
import org.openapitools.client.model.DeferredBilling;
import org.threeten.bp.LocalDate;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContractRequest
 */
public class ContractRequestTest {
    private final ContractRequest model = new ContractRequest();

    /**
     * Model tests for ContractRequest
     */
    @Test
    public void testContractRequest() {
        // TODO: test ContractRequest
    }

    /**
     * Test the property 'productRef'
     */
    @Test
    public void productRefTest() {
        // TODO: test productRef
    }

    /**
     * Test the property 'contractType'
     */
    @Test
    public void contractTypeTest() {
        // TODO: test contractType
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'signedAt'
     */
    @Test
    public void signedAtTest() {
        // TODO: test signedAt
    }

    /**
     * Test the property 'activatedAt'
     */
    @Test
    public void activatedAtTest() {
        // TODO: test activatedAt
    }

    /**
     * Test the property 'expireAt'
     */
    @Test
    public void expireAtTest() {
        // TODO: test expireAt
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'distributor'
     */
    @Test
    public void distributorTest() {
        // TODO: test distributor
    }

    /**
     * Test the property 'subscriber'
     */
    @Test
    public void subscriberTest() {
        // TODO: test subscriber
    }

    /**
     * Test the property 'custom'
     */
    @Test
    public void customTest() {
        // TODO: test custom
    }

}
