/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessAddress;
import org.openapitools.client.model.EligibilityResponseBillingInProgress;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EligibilityResponse
 */
public class EligibilityResponseTest {
    private final EligibilityResponse model = new EligibilityResponse();

    /**
     * Model tests for EligibilityResponse
     */
    @Test
    public void testEligibilityResponse() {
        // TODO: test EligibilityResponse
    }

    /**
     * Test the property 'customerRef'
     */
    @Test
    public void customerRefTest() {
        // TODO: test customerRef
    }

    /**
     * Test the property 'subscriptionRef'
     */
    @Test
    public void subscriptionRefTest() {
        // TODO: test subscriptionRef
    }

    /**
     * Test the property 'contractRef'
     */
    @Test
    public void contractRefTest() {
        // TODO: test contractRef
    }

    /**
     * Test the property 'contractStatus'
     */
    @Test
    public void contractStatusTest() {
        // TODO: test contractStatus
    }

    /**
     * Test the property 'billingAddress'
     */
    @Test
    public void billingAddressTest() {
        // TODO: test billingAddress
    }

    /**
     * Test the property 'billingInProgress'
     */
    @Test
    public void billingInProgressTest() {
        // TODO: test billingInProgress
    }

}
