/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EligibilityResponseBillingInProgress
 */
public class EligibilityResponseBillingInProgressTest {
    private final EligibilityResponseBillingInProgress model = new EligibilityResponseBillingInProgress();

    /**
     * Model tests for EligibilityResponseBillingInProgress
     */
    @Test
    public void testEligibilityResponseBillingInProgress() {
        // TODO: test EligibilityResponseBillingInProgress
    }

    /**
     * Test the property 'amountWithoutTax'
     */
    @Test
    public void amountWithoutTaxTest() {
        // TODO: test amountWithoutTax
    }

    /**
     * Test the property 'amountTax'
     */
    @Test
    public void amountTaxTest() {
        // TODO: test amountTax
    }

    /**
     * Test the property 'amountWithTax'
     */
    @Test
    public void amountWithTaxTest() {
        // TODO: test amountWithTax
    }

    /**
     * Test the property 'amountEcoParticipation'
     */
    @Test
    public void amountEcoParticipationTest() {
        // TODO: test amountEcoParticipation
    }

}
