/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OperationResponseAllOfBilling
 */
public class OperationResponseAllOfBillingTest {
    private final OperationResponseAllOfBilling model = new OperationResponseAllOfBilling();

    /**
     * Model tests for OperationResponseAllOfBilling
     */
    @Test
    public void testOperationResponseAllOfBilling() {
        // TODO: test OperationResponseAllOfBilling
    }

    /**
     * Test the property 'subscriptionRef'
     */
    @Test
    public void subscriptionRefTest() {
        // TODO: test subscriptionRef
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

}
