/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OperationRequestOrderProductItems
 */
public class OperationRequestOrderProductItemsTest {
    private final OperationRequestOrderProductItems model = new OperationRequestOrderProductItems();

    /**
     * Model tests for OperationRequestOrderProductItems
     */
    @Test
    public void testOperationRequestOrderProductItems() {
        // TODO: test OperationRequestOrderProductItems
    }

    /**
     * Test the property 'productRef'
     */
    @Test
    public void productRefTest() {
        // TODO: test productRef
    }

    /**
     * Test the property 'productLabel'
     */
    @Test
    public void productLabelTest() {
        // TODO: test productLabel
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'packaging'
     */
    @Test
    public void packagingTest() {
        // TODO: test packaging
    }

    /**
     * Test the property 'unitPrice'
     */
    @Test
    public void unitPriceTest() {
        // TODO: test unitPrice
    }

    /**
     * Test the property 'vatRate'
     */
    @Test
    public void vatRateTest() {
        // TODO: test vatRate
    }

    /**
     * Test the property 'amountWithoutTax'
     */
    @Test
    public void amountWithoutTaxTest() {
        // TODO: test amountWithoutTax
    }

    /**
     * Test the property 'amountTax'
     */
    @Test
    public void amountTaxTest() {
        // TODO: test amountTax
    }

    /**
     * Test the property 'amountWithTax'
     */
    @Test
    public void amountWithTaxTest() {
        // TODO: test amountWithTax
    }

    /**
     * Test the property 'amountEcoParticipation'
     */
    @Test
    public void amountEcoParticipationTest() {
        // TODO: test amountEcoParticipation
    }

}
