/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.OperationResponseAllOfBilling;
import org.openapitools.client.model.OperationResponseAllOfInvoice;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OperationResponseAllOf
 */
public class OperationResponseAllOfTest {
    private final OperationResponseAllOf model = new OperationResponseAllOf();

    /**
     * Model tests for OperationResponseAllOf
     */
    @Test
    public void testOperationResponseAllOf() {
        // TODO: test OperationResponseAllOf
    }

    /**
     * Test the property 'operationId'
     */
    @Test
    public void operationIdTest() {
        // TODO: test operationId
    }

    /**
     * Test the property 'operationRef'
     */
    @Test
    public void operationRefTest() {
        // TODO: test operationRef
    }

    /**
     * Test the property 'billing'
     */
    @Test
    public void billingTest() {
        // TODO: test billing
    }

    /**
     * Test the property 'invoice'
     */
    @Test
    public void invoiceTest() {
        // TODO: test invoice
    }

}
