/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.OperationRequestOrderOrderItems;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OperationRequestOrder
 */
public class OperationRequestOrderTest {
    private final OperationRequestOrder model = new OperationRequestOrder();

    /**
     * Model tests for OperationRequestOrder
     */
    @Test
    public void testOperationRequestOrder() {
        // TODO: test OperationRequestOrder
    }

    /**
     * Test the property 'orderRef'
     */
    @Test
    public void orderRefTest() {
        // TODO: test orderRef
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'orderType'
     */
    @Test
    public void orderTypeTest() {
        // TODO: test orderType
    }

    /**
     * Test the property 'orderItems'
     */
    @Test
    public void orderItemsTest() {
        // TODO: test orderItems
    }

    /**
     * Test the property 'totalWithoutTax'
     */
    @Test
    public void totalWithoutTaxTest() {
        // TODO: test totalWithoutTax
    }

    /**
     * Test the property 'totalTax'
     */
    @Test
    public void totalTaxTest() {
        // TODO: test totalTax
    }

    /**
     * Test the property 'totalWithTax'
     */
    @Test
    public void totalWithTaxTest() {
        // TODO: test totalWithTax
    }

    /**
     * Test the property 'amountEcoParticipation'
     */
    @Test
    public void amountEcoParticipationTest() {
        // TODO: test amountEcoParticipation
    }

}
