/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.OperationRequest;
import org.openapitools.client.model.OperationRequestOrder;
import org.openapitools.client.model.OperationResponseAllOf;
import org.openapitools.client.model.OperationResponseAllOfBilling;
import org.openapitools.client.model.OperationResponseAllOfInvoice;
import org.threeten.bp.LocalDate;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OperationResponse
 */
public class OperationResponseTest {
    private final OperationResponse model = new OperationResponse();

    /**
     * Model tests for OperationResponse
     */
    @Test
    public void testOperationResponse() {
        // TODO: test OperationResponse
    }

    /**
     * Test the property 'operationId'
     */
    @Test
    public void operationIdTest() {
        // TODO: test operationId
    }

    /**
     * Test the property 'operationRef'
     */
    @Test
    public void operationRefTest() {
        // TODO: test operationRef
    }

    /**
     * Test the property 'billing'
     */
    @Test
    public void billingTest() {
        // TODO: test billing
    }

    /**
     * Test the property 'invoice'
     */
    @Test
    public void invoiceTest() {
        // TODO: test invoice
    }

    /**
     * Test the property 'customerRef'
     */
    @Test
    public void customerRefTest() {
        // TODO: test customerRef
    }

    /**
     * Test the property 'operationAt'
     */
    @Test
    public void operationAtTest() {
        // TODO: test operationAt
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

}
