/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessBuyer;
import org.openapitools.client.model.BusinessContract;
import org.openapitools.client.model.BusinessPayment;
import org.openapitools.client.model.BusinessSeller;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubscriptionRequest
 */
public class SubscriptionRequestTest {
    private final SubscriptionRequest model = new SubscriptionRequest();

    /**
     * Model tests for SubscriptionRequest
     */
    @Test
    public void testSubscriptionRequest() {
        // TODO: test SubscriptionRequest
    }

    /**
     * Test the property 'subscriptionType'
     */
    @Test
    public void subscriptionTypeTest() {
        // TODO: test subscriptionType
    }

    /**
     * Test the property 'contract'
     */
    @Test
    public void contractTest() {
        // TODO: test contract
    }

    /**
     * Test the property 'seller'
     */
    @Test
    public void sellerTest() {
        // TODO: test seller
    }

    /**
     * Test the property 'buyer'
     */
    @Test
    public void buyerTest() {
        // TODO: test buyer
    }

    /**
     * Test the property 'payment'
     */
    @Test
    public void paymentTest() {
        // TODO: test payment
    }

}
