/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ContractActionRequest;
import org.openapitools.client.model.ContractRequest;
import org.openapitools.client.model.ContractResponse;
import org.openapitools.client.model.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CreateLifecycleApi
 */
@Ignore
public class CreateLifecycleApiTest {

    private final CreateLifecycleApi api = new CreateLifecycleApi();

    
    /**
     * Patch a Contract
     *
     * Update an existing Contract
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchContractTest() throws ApiException {
        String contractRef = null;
        ContractActionRequest contractActionRequest = null;
        api.patchContract(contractRef, contractActionRequest);

        // TODO: test validations
    }
    
    /**
     * Add a Contract
     *
     * Add a new Contract
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postContractTest() throws ApiException {
        ContractRequest contractRequest = null;
        ContractResponse response = api.postContract(contractRequest);

        // TODO: test validations
    }
    
}
