/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.EligibilityResponse;
import org.openapitools.client.model.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EligibilityApi
 */
@Ignore
public class EligibilityApiTest {

    private final EligibilityApi api = new EligibilityApi();

    
    /**
     * Rerieves Eligibility status
     *
     * Gives the status of customers with respect to the subscription. Ccontract and payment information are checked.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readEligibilityTest() throws ApiException {
        String customerRef = null;
        EligibilityResponse response = api.readEligibility(customerRef);

        // TODO: test validations
    }
    
}
