/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.InlineResponse200;
import org.openapitools.client.model.InlineResponse2001;
import org.openapitools.client.model.Invoice;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Phase2Api
 */
@Ignore
public class Phase2ApiTest {

    private final Phase2Api api = new Phase2Api();

    
    /**
     * 
     *
     * Returns a list of Invoices
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invoicesGetTest() throws ApiException {
        String subscriptionId = null;
        String contractRef = null;
        String customerRef = null;
        String contactRef = null;
        Integer limit = null;
        Integer offset = null;
        InlineResponse2001 response = api.invoicesGet(subscriptionId, contractRef, customerRef, contactRef, limit, offset);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns an invoice
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invoicesInvoiceRefGetTest() throws ApiException {
        String invoiceRef = null;
        Invoice response = api.invoicesInvoiceRefGet(invoiceRef);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns a list of Operation added to deferred billing
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operationsGetTest() throws ApiException {
        String subscriptionId = null;
        String invoiceRef = null;
        String customerRef = null;
        String contactRef = null;
        Integer limit = null;
        Integer offset = null;
        InlineResponse200 response = api.operationsGet(subscriptionId, invoiceRef, customerRef, contactRef, limit, offset);

        // TODO: test validations
    }
    
}
