/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.SubscriptionRequest;
import org.openapitools.client.model.SubscriptionResponse;
import org.openapitools.client.model.SubscriptionsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionsApi
 */
@Ignore
public class SubscriptionsApiTest {

    private final SubscriptionsApi api = new SubscriptionsApi();

    
    /**
     * Read Subscription
     *
     * Get an existing Subscription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSubscriptionTest() throws ApiException {
        String subscriptionRef = null;
        SubscriptionResponse response = api.getSubscription(subscriptionRef);

        // TODO: test validations
    }
    
    /**
     * Patch Subscription
     *
     * Update an existing Subscription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchSubscriptionTest() throws ApiException {
        String subscriptionRef = null;
        SubscriptionRequest subscriptionRequest = null;
        SubscriptionResponse response = api.patchSubscription(subscriptionRef, subscriptionRequest);

        // TODO: test validations
    }
    
    /**
     * Add Subscriptions
     *
     * Add a new Subscription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postSubscriptionTest() throws ApiException {
        SubscriptionRequest subscriptionRequest = null;
        SubscriptionResponse response = api.postSubscription(subscriptionRequest);

        // TODO: test validations
    }
    
    /**
     * Search Subscriptions
     *
     * Multi-criteria search for subscriptions. The result is a list (maybe empty) of subscriptions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchSubscriptionsTest() throws ApiException {
        String contractRef = null;
        String customerRef = null;
        String contractStatus = null;
        Integer limit = null;
        Integer offset = null;
        SubscriptionsResponse response = api.searchSubscriptions(contractRef, customerRef, contractStatus, limit, offset);

        // TODO: test validations
    }
    
}
