/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Desribes professionnal party
 */
@ApiModel(description = "Desribes professionnal party")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:18:57.613106+02:00[Europe/Paris]")
public class BusinessProfessionnalPartyProfessionnal {
  public static final String SERIALIZED_NAME_CUSTOMER_ID = "customerId";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ID)
  private String customerId;

  public static final String SERIALIZED_NAME_CUSTOMER_REF = "customerRef";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_REF)
  private String customerRef;


  public BusinessProfessionnalPartyProfessionnal customerId(String customerId) {
    
    this.customerId = customerId;
    return this;
  }

   /**
   * Internal Identifier of organisation
   * @return customerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "PRO-8996786873", value = "Internal Identifier of organisation")

  public String getCustomerId() {
    return customerId;
  }


  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }


  public BusinessProfessionnalPartyProfessionnal customerRef(String customerRef) {
    
    this.customerRef = customerRef;
    return this;
  }

   /**
   * External identifier of organisation (i.e. CUSTOMER)
   * @return customerRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "CUSTOMER NUMBER", value = "External identifier of organisation (i.e. CUSTOMER)")

  public String getCustomerRef() {
    return customerRef;
  }


  public void setCustomerRef(String customerRef) {
    this.customerRef = customerRef;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessProfessionnalPartyProfessionnal businessProfessionnalPartyProfessionnal = (BusinessProfessionnalPartyProfessionnal) o;
    return Objects.equals(this.customerId, businessProfessionnalPartyProfessionnal.customerId) &&
        Objects.equals(this.customerRef, businessProfessionnalPartyProfessionnal.customerRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, customerRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessProfessionnalPartyProfessionnal {\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    customerRef: ").append(toIndentedString(customerRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

