/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessAddress;
import org.openapitools.client.model.BusinessPerson;
import org.openapitools.client.model.BusinessSellerEFacturation;

/**
 * Describes seller organisation &amp; contact
 */
@ApiModel(description = "Describes seller organisation & contact")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:16:14.922776+02:00[Europe/Paris]")
public class BusinessSeller {
  public static final String SERIALIZED_NAME_SELLER_REF = "sellerRef";
  @SerializedName(SERIALIZED_NAME_SELLER_REF)
  private String sellerRef;

  public static final String SERIALIZED_NAME_E_FACTURATION = "eFacturation";
  @SerializedName(SERIALIZED_NAME_E_FACTURATION)
  private BusinessSellerEFacturation eFacturation;

  public static final String SERIALIZED_NAME_CONTACT_PERSON = "contactPerson";
  @SerializedName(SERIALIZED_NAME_CONTACT_PERSON)
  private BusinessPerson contactPerson;

  public static final String SERIALIZED_NAME_CONTACT_ADDRESS = "contactAddress";
  @SerializedName(SERIALIZED_NAME_CONTACT_ADDRESS)
  private BusinessAddress contactAddress;


  public BusinessSeller sellerRef(String sellerRef) {
    
    this.sellerRef = sellerRef;
    return this;
  }

   /**
   * External reference of seller
   * @return sellerRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "esgi SA", value = "External reference of seller")

  public String getSellerRef() {
    return sellerRef;
  }


  public void setSellerRef(String sellerRef) {
    this.sellerRef = sellerRef;
  }


  public BusinessSeller eFacturation(BusinessSellerEFacturation eFacturation) {
    
    this.eFacturation = eFacturation;
    return this;
  }

   /**
   * Get eFacturation
   * @return eFacturation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessSellerEFacturation geteFacturation() {
    return eFacturation;
  }


  public void seteFacturation(BusinessSellerEFacturation eFacturation) {
    this.eFacturation = eFacturation;
  }


  public BusinessSeller contactPerson(BusinessPerson contactPerson) {
    
    this.contactPerson = contactPerson;
    return this;
  }

   /**
   * Get contactPerson
   * @return contactPerson
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessPerson getContactPerson() {
    return contactPerson;
  }


  public void setContactPerson(BusinessPerson contactPerson) {
    this.contactPerson = contactPerson;
  }


  public BusinessSeller contactAddress(BusinessAddress contactAddress) {
    
    this.contactAddress = contactAddress;
    return this;
  }

   /**
   * Get contactAddress
   * @return contactAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessAddress getContactAddress() {
    return contactAddress;
  }


  public void setContactAddress(BusinessAddress contactAddress) {
    this.contactAddress = contactAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessSeller businessSeller = (BusinessSeller) o;
    return Objects.equals(this.sellerRef, businessSeller.sellerRef) &&
        Objects.equals(this.eFacturation, businessSeller.eFacturation) &&
        Objects.equals(this.contactPerson, businessSeller.contactPerson) &&
        Objects.equals(this.contactAddress, businessSeller.contactAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sellerRef, eFacturation, contactPerson, contactAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessSeller {\n");
    sb.append("    sellerRef: ").append(toIndentedString(sellerRef)).append("\n");
    sb.append("    eFacturation: ").append(toIndentedString(eFacturation)).append("\n");
    sb.append("    contactPerson: ").append(toIndentedString(contactPerson)).append("\n");
    sb.append("    contactAddress: ").append(toIndentedString(contactAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

