/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessAddress;
import org.openapitools.client.model.BusinessBuyerEInvoicing;
import org.openapitools.client.model.BusinessPerson;
import org.openapitools.client.model.BusinessProfessionnalParty;

/**
 * Describes buyer organisation &amp; contact
 */
@ApiModel(description = "Describes buyer organisation & contact")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:16:14.922776+02:00[Europe/Paris]")
public class BusinessBuyer {
  public static final String SERIALIZED_NAME_BUYER_REF = "buyerRef";
  @SerializedName(SERIALIZED_NAME_BUYER_REF)
  private String buyerRef;

  /**
   * Gets or Sets buyerType
   */
  @JsonAdapter(BuyerTypeEnum.Adapter.class)
  public enum BuyerTypeEnum {
    PARTICULAR("PARTICULAR"),
    
    PROFESSIONNAL("PROFESSIONNAL");

    private String value;

    BuyerTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BuyerTypeEnum fromValue(String value) {
      for (BuyerTypeEnum b : BuyerTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BuyerTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BuyerTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BuyerTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BuyerTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_BUYER_TYPE = "buyerType";
  @SerializedName(SERIALIZED_NAME_BUYER_TYPE)
  private BuyerTypeEnum buyerType;

  public static final String SERIALIZED_NAME_PARTY = "party";
  @SerializedName(SERIALIZED_NAME_PARTY)
  private BusinessProfessionnalParty party;

  public static final String SERIALIZED_NAME_E_INVOICING = "eInvoicing";
  @SerializedName(SERIALIZED_NAME_E_INVOICING)
  private BusinessBuyerEInvoicing eInvoicing;

  public static final String SERIALIZED_NAME_CONTACT_PERSON = "contactPerson";
  @SerializedName(SERIALIZED_NAME_CONTACT_PERSON)
  private BusinessPerson contactPerson;

  public static final String SERIALIZED_NAME_CONTACT_ADDRESS = "contactAddress";
  @SerializedName(SERIALIZED_NAME_CONTACT_ADDRESS)
  private BusinessAddress contactAddress;

  public static final String SERIALIZED_NAME_BILLING_ADDRESS = "billingAddress";
  @SerializedName(SERIALIZED_NAME_BILLING_ADDRESS)
  private BusinessAddress billingAddress;


  public BusinessBuyer buyerRef(String buyerRef) {
    
    this.buyerRef = buyerRef;
    return this;
  }

   /**
   * External reference of buyer (By example: social reason of the company)
   * @return buyerRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Ma Petite Entreprise", value = "External reference of buyer (By example: social reason of the company)")

  public String getBuyerRef() {
    return buyerRef;
  }


  public void setBuyerRef(String buyerRef) {
    this.buyerRef = buyerRef;
  }


  public BusinessBuyer buyerType(BuyerTypeEnum buyerType) {
    
    this.buyerType = buyerType;
    return this;
  }

   /**
   * Get buyerType
   * @return buyerType
  **/
  @ApiModelProperty(example = "PROFESSIONNAL", required = true, value = "")

  public BuyerTypeEnum getBuyerType() {
    return buyerType;
  }


  public void setBuyerType(BuyerTypeEnum buyerType) {
    this.buyerType = buyerType;
  }


  public BusinessBuyer party(BusinessProfessionnalParty party) {
    
    this.party = party;
    return this;
  }

   /**
   * Get party
   * @return party
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessProfessionnalParty getParty() {
    return party;
  }


  public void setParty(BusinessProfessionnalParty party) {
    this.party = party;
  }


  public BusinessBuyer eInvoicing(BusinessBuyerEInvoicing eInvoicing) {
    
    this.eInvoicing = eInvoicing;
    return this;
  }

   /**
   * Get eInvoicing
   * @return eInvoicing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessBuyerEInvoicing geteInvoicing() {
    return eInvoicing;
  }


  public void seteInvoicing(BusinessBuyerEInvoicing eInvoicing) {
    this.eInvoicing = eInvoicing;
  }


  public BusinessBuyer contactPerson(BusinessPerson contactPerson) {
    
    this.contactPerson = contactPerson;
    return this;
  }

   /**
   * Get contactPerson
   * @return contactPerson
  **/
  @ApiModelProperty(required = true, value = "")

  public BusinessPerson getContactPerson() {
    return contactPerson;
  }


  public void setContactPerson(BusinessPerson contactPerson) {
    this.contactPerson = contactPerson;
  }


  public BusinessBuyer contactAddress(BusinessAddress contactAddress) {
    
    this.contactAddress = contactAddress;
    return this;
  }

   /**
   * Get contactAddress
   * @return contactAddress
  **/
  @ApiModelProperty(required = true, value = "")

  public BusinessAddress getContactAddress() {
    return contactAddress;
  }


  public void setContactAddress(BusinessAddress contactAddress) {
    this.contactAddress = contactAddress;
  }


  public BusinessBuyer billingAddress(BusinessAddress billingAddress) {
    
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * Get billingAddress
   * @return billingAddress
  **/
  @ApiModelProperty(required = true, value = "")

  public BusinessAddress getBillingAddress() {
    return billingAddress;
  }


  public void setBillingAddress(BusinessAddress billingAddress) {
    this.billingAddress = billingAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessBuyer businessBuyer = (BusinessBuyer) o;
    return Objects.equals(this.buyerRef, businessBuyer.buyerRef) &&
        Objects.equals(this.buyerType, businessBuyer.buyerType) &&
        Objects.equals(this.party, businessBuyer.party) &&
        Objects.equals(this.eInvoicing, businessBuyer.eInvoicing) &&
        Objects.equals(this.contactPerson, businessBuyer.contactPerson) &&
        Objects.equals(this.contactAddress, businessBuyer.contactAddress) &&
        Objects.equals(this.billingAddress, businessBuyer.billingAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buyerRef, buyerType, party, eInvoicing, contactPerson, contactAddress, billingAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessBuyer {\n");
    sb.append("    buyerRef: ").append(toIndentedString(buyerRef)).append("\n");
    sb.append("    buyerType: ").append(toIndentedString(buyerType)).append("\n");
    sb.append("    party: ").append(toIndentedString(party)).append("\n");
    sb.append("    eInvoicing: ").append(toIndentedString(eInvoicing)).append("\n");
    sb.append("    contactPerson: ").append(toIndentedString(contactPerson)).append("\n");
    sb.append("    contactAddress: ").append(toIndentedString(contactAddress)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

