/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Necessary for e-Invoicing &amp; e-Reporting
 */
@ApiModel(description = "Necessary for e-Invoicing & e-Reporting")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:16:14.922776+02:00[Europe/Paris]")
public class BusinessSellerEFacturation {
  public static final String SERIALIZED_NAME_SIREN = "siren";
  @SerializedName(SERIALIZED_NAME_SIREN)
  private String siren;

  public static final String SERIALIZED_NAME_TVA_INTRACOMMUNAUTAIRE = "tvaIntracommunautaire";
  @SerializedName(SERIALIZED_NAME_TVA_INTRACOMMUNAUTAIRE)
  private String tvaIntracommunautaire;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;


  public BusinessSellerEFacturation siren(String siren) {
    
    this.siren = siren;
    return this;
  }

   /**
   * Get siren
   * @return siren
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "356000000", value = "")

  public String getSiren() {
    return siren;
  }


  public void setSiren(String siren) {
    this.siren = siren;
  }


  public BusinessSellerEFacturation tvaIntracommunautaire(String tvaIntracommunautaire) {
    
    this.tvaIntracommunautaire = tvaIntracommunautaire;
    return this;
  }

   /**
   * Get tvaIntracommunautaire
   * @return tvaIntracommunautaire
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "FR39356000000", value = "")

  public String getTvaIntracommunautaire() {
    return tvaIntracommunautaire;
  }


  public void setTvaIntracommunautaire(String tvaIntracommunautaire) {
    this.tvaIntracommunautaire = tvaIntracommunautaire;
  }


  public BusinessSellerEFacturation country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "FRANCE", value = "")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessSellerEFacturation businessSellerEFacturation = (BusinessSellerEFacturation) o;
    return Objects.equals(this.siren, businessSellerEFacturation.siren) &&
        Objects.equals(this.tvaIntracommunautaire, businessSellerEFacturation.tvaIntracommunautaire) &&
        Objects.equals(this.country, businessSellerEFacturation.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(siren, tvaIntracommunautaire, country);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessSellerEFacturation {\n");
    sb.append("    siren: ").append(toIndentedString(siren)).append("\n");
    sb.append("    tvaIntracommunautaire: ").append(toIndentedString(tvaIntracommunautaire)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

