/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ContractResponseAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:18:57.613106+02:00[Europe/Paris]")
public class ContractResponseAllOf {
  public static final String SERIALIZED_NAME_CONTRACT_ID = "contractId";
  @SerializedName(SERIALIZED_NAME_CONTRACT_ID)
  private Integer contractId;

  public static final String SERIALIZED_NAME_CONTRACT_REF = "contractRef";
  @SerializedName(SERIALIZED_NAME_CONTRACT_REF)
  private String contractRef;


  public ContractResponseAllOf contractId(Integer contractId) {
    
    this.contractId = contractId;
    return this;
  }

   /**
   * Internal identifier of the contract
   * @return contractId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "58761542", value = "Internal identifier of the contract")

  public Integer getContractId() {
    return contractId;
  }


  public void setContractId(Integer contractId) {
    this.contractId = contractId;
  }


  public ContractResponseAllOf contractRef(String contractRef) {
    
    this.contractRef = contractRef;
    return this;
  }

   /**
   * External identifier of the contract
   * @return contractRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "SUB-YTYE65687", value = "External identifier of the contract")

  public String getContractRef() {
    return contractRef;
  }


  public void setContractRef(String contractRef) {
    this.contractRef = contractRef;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractResponseAllOf contractResponseAllOf = (ContractResponseAllOf) o;
    return Objects.equals(this.contractId, contractResponseAllOf.contractId) &&
        Objects.equals(this.contractRef, contractResponseAllOf.contractRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractId, contractRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractResponseAllOf {\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    contractRef: ").append(toIndentedString(contractRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

