/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessAddress;
import org.openapitools.client.model.EligibilityResponseBillingInProgress;

/**
 * Returns
 */
@ApiModel(description = "Returns")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:16:14.922776+02:00[Europe/Paris]")
public class EligibilityResponse {
  public static final String SERIALIZED_NAME_CUSTOMER_REF = "customerRef";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_REF)
  private String customerRef;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_REF = "subscriptionRef";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_REF)
  private String subscriptionRef;

  public static final String SERIALIZED_NAME_CONTRACT_REF = "contractRef";
  @SerializedName(SERIALIZED_NAME_CONTRACT_REF)
  private String contractRef;

  public static final String SERIALIZED_NAME_CONTRACT_STATUS = "contractStatus";
  @SerializedName(SERIALIZED_NAME_CONTRACT_STATUS)
  private String contractStatus;

  public static final String SERIALIZED_NAME_BILLING_ADDRESS = "billingAddress";
  @SerializedName(SERIALIZED_NAME_BILLING_ADDRESS)
  private BusinessAddress billingAddress;

  public static final String SERIALIZED_NAME_BILLING_IN_PROGRESS = "billingInProgress";
  @SerializedName(SERIALIZED_NAME_BILLING_IN_PROGRESS)
  private EligibilityResponseBillingInProgress billingInProgress;


  public EligibilityResponse customerRef(String customerRef) {
    
    this.customerRef = customerRef;
    return this;
  }

   /**
   * Get customerRef
   * @return customerRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCustomerRef() {
    return customerRef;
  }


  public void setCustomerRef(String customerRef) {
    this.customerRef = customerRef;
  }


  public EligibilityResponse subscriptionRef(String subscriptionRef) {
    
    this.subscriptionRef = subscriptionRef;
    return this;
  }

   /**
   * Get subscriptionRef
   * @return subscriptionRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubscriptionRef() {
    return subscriptionRef;
  }


  public void setSubscriptionRef(String subscriptionRef) {
    this.subscriptionRef = subscriptionRef;
  }


  public EligibilityResponse contractRef(String contractRef) {
    
    this.contractRef = contractRef;
    return this;
  }

   /**
   * Get contractRef
   * @return contractRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getContractRef() {
    return contractRef;
  }


  public void setContractRef(String contractRef) {
    this.contractRef = contractRef;
  }


  public EligibilityResponse contractStatus(String contractStatus) {
    
    this.contractStatus = contractStatus;
    return this;
  }

   /**
   * Get contractStatus
   * @return contractStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getContractStatus() {
    return contractStatus;
  }


  public void setContractStatus(String contractStatus) {
    this.contractStatus = contractStatus;
  }


  public EligibilityResponse billingAddress(BusinessAddress billingAddress) {
    
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * Get billingAddress
   * @return billingAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessAddress getBillingAddress() {
    return billingAddress;
  }


  public void setBillingAddress(BusinessAddress billingAddress) {
    this.billingAddress = billingAddress;
  }


  public EligibilityResponse billingInProgress(EligibilityResponseBillingInProgress billingInProgress) {
    
    this.billingInProgress = billingInProgress;
    return this;
  }

   /**
   * Get billingInProgress
   * @return billingInProgress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EligibilityResponseBillingInProgress getBillingInProgress() {
    return billingInProgress;
  }


  public void setBillingInProgress(EligibilityResponseBillingInProgress billingInProgress) {
    this.billingInProgress = billingInProgress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EligibilityResponse eligibilityResponse = (EligibilityResponse) o;
    return Objects.equals(this.customerRef, eligibilityResponse.customerRef) &&
        Objects.equals(this.subscriptionRef, eligibilityResponse.subscriptionRef) &&
        Objects.equals(this.contractRef, eligibilityResponse.contractRef) &&
        Objects.equals(this.contractStatus, eligibilityResponse.contractStatus) &&
        Objects.equals(this.billingAddress, eligibilityResponse.billingAddress) &&
        Objects.equals(this.billingInProgress, eligibilityResponse.billingInProgress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerRef, subscriptionRef, contractRef, contractStatus, billingAddress, billingInProgress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EligibilityResponse {\n");
    sb.append("    customerRef: ").append(toIndentedString(customerRef)).append("\n");
    sb.append("    subscriptionRef: ").append(toIndentedString(subscriptionRef)).append("\n");
    sb.append("    contractRef: ").append(toIndentedString(contractRef)).append("\n");
    sb.append("    contractStatus: ").append(toIndentedString(contractStatus)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("    billingInProgress: ").append(toIndentedString(billingInProgress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

