/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.OperationRequestOrder;
import org.threeten.bp.LocalDate;

/**
 * Describes an Operation added to deferred billing
 */
@ApiModel(description = "Describes an Operation added to deferred billing")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:16:14.922776+02:00[Europe/Paris]")
public class OperationRequest {
  public static final String SERIALIZED_NAME_CUSTOMER_REF = "customerRef";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_REF)
  private String customerRef;

  public static final String SERIALIZED_NAME_OPERATION_AT = "operationAt";
  @SerializedName(SERIALIZED_NAME_OPERATION_AT)
  private LocalDate operationAt;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  private OperationRequestOrder order;


  public OperationRequest customerRef(String customerRef) {
    
    this.customerRef = customerRef;
    return this;
  }

   /**
   * External identifier of the Customer
   * @return customerRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "HA-8768376537", value = "External identifier of the Customer")

  public String getCustomerRef() {
    return customerRef;
  }


  public void setCustomerRef(String customerRef) {
    this.customerRef = customerRef;
  }


  public OperationRequest operationAt(LocalDate operationAt) {
    
    this.operationAt = operationAt;
    return this;
  }

   /**
   * Transaction date in the sales system as defined in ISO 8601 ([more information about the standar](https://www.iso.org/fr/iso-8601-date-and-time-format.html)).  Used format : YYYY-MM-DD 
   * @return operationAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Wed Apr 27 02:00:00 CEST 2022", value = "Transaction date in the sales system as defined in ISO 8601 ([more information about the standar](https://www.iso.org/fr/iso-8601-date-and-time-format.html)).  Used format : YYYY-MM-DD ")

  public LocalDate getOperationAt() {
    return operationAt;
  }


  public void setOperationAt(LocalDate operationAt) {
    this.operationAt = operationAt;
  }


  public OperationRequest order(OperationRequestOrder order) {
    
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OperationRequestOrder getOrder() {
    return order;
  }


  public void setOrder(OperationRequestOrder order) {
    this.order = order;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationRequest operationRequest = (OperationRequest) o;
    return Objects.equals(this.customerRef, operationRequest.customerRef) &&
        Objects.equals(this.operationAt, operationRequest.operationAt) &&
        Objects.equals(this.order, operationRequest.order);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerRef, operationAt, order);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationRequest {\n");
    sb.append("    customerRef: ").append(toIndentedString(customerRef)).append("\n");
    sb.append("    operationAt: ").append(toIndentedString(operationAt)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

