/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.OperationResponseAllOfBilling;
import org.openapitools.client.model.OperationResponseAllOfInvoice;

/**
 * OperationResponseAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:16:14.922776+02:00[Europe/Paris]")
public class OperationResponseAllOf {
  public static final String SERIALIZED_NAME_OPERATION_ID = "operationId";
  @SerializedName(SERIALIZED_NAME_OPERATION_ID)
  private Integer operationId;

  public static final String SERIALIZED_NAME_OPERATION_REF = "operationRef";
  @SerializedName(SERIALIZED_NAME_OPERATION_REF)
  private String operationRef;

  public static final String SERIALIZED_NAME_BILLING = "billing";
  @SerializedName(SERIALIZED_NAME_BILLING)
  private OperationResponseAllOfBilling billing;

  public static final String SERIALIZED_NAME_INVOICE = "invoice";
  @SerializedName(SERIALIZED_NAME_INVOICE)
  private OperationResponseAllOfInvoice invoice;


  public OperationResponseAllOf operationId(Integer operationId) {
    
    this.operationId = operationId;
    return this;
  }

   /**
   * Internal identifier of the Operation
   * @return operationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Internal identifier of the Operation")

  public Integer getOperationId() {
    return operationId;
  }


  public void setOperationId(Integer operationId) {
    this.operationId = operationId;
  }


  public OperationResponseAllOf operationRef(String operationRef) {
    
    this.operationRef = operationRef;
    return this;
  }

   /**
   * External identifier of the Operation
   * @return operationRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "HA-8768376537", value = "External identifier of the Operation")

  public String getOperationRef() {
    return operationRef;
  }


  public void setOperationRef(String operationRef) {
    this.operationRef = operationRef;
  }


  public OperationResponseAllOf billing(OperationResponseAllOfBilling billing) {
    
    this.billing = billing;
    return this;
  }

   /**
   * Get billing
   * @return billing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OperationResponseAllOfBilling getBilling() {
    return billing;
  }


  public void setBilling(OperationResponseAllOfBilling billing) {
    this.billing = billing;
  }


  public OperationResponseAllOf invoice(OperationResponseAllOfInvoice invoice) {
    
    this.invoice = invoice;
    return this;
  }

   /**
   * Get invoice
   * @return invoice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OperationResponseAllOfInvoice getInvoice() {
    return invoice;
  }


  public void setInvoice(OperationResponseAllOfInvoice invoice) {
    this.invoice = invoice;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationResponseAllOf operationResponseAllOf = (OperationResponseAllOf) o;
    return Objects.equals(this.operationId, operationResponseAllOf.operationId) &&
        Objects.equals(this.operationRef, operationResponseAllOf.operationRef) &&
        Objects.equals(this.billing, operationResponseAllOf.billing) &&
        Objects.equals(this.invoice, operationResponseAllOf.invoice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationId, operationRef, billing, invoice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationResponseAllOf {\n");
    sb.append("    operationId: ").append(toIndentedString(operationId)).append("\n");
    sb.append("    operationRef: ").append(toIndentedString(operationRef)).append("\n");
    sb.append("    billing: ").append(toIndentedString(billing)).append("\n");
    sb.append("    invoice: ").append(toIndentedString(invoice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

