/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.BusinessAddress;
import org.openapitools.client.model.BusinessPerson;
import org.openapitools.client.model.OperationRequestOrderProductItems;
import org.threeten.bp.LocalDate;

/**
 * OperationRequestOrderOrderItems
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:16:14.922776+02:00[Europe/Paris]")
public class OperationRequestOrderOrderItems {
  public static final String SERIALIZED_NAME_SHIPMENT_ADDRESS = "shipmentAddress";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_ADDRESS)
  private BusinessAddress shipmentAddress;

  public static final String SERIALIZED_NAME_SHIPMENT_CONTACT = "shipmentContact";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_CONTACT)
  private BusinessPerson shipmentContact;

  public static final String SERIALIZED_NAME_DELIVERED_ON = "deliveredOn";
  @SerializedName(SERIALIZED_NAME_DELIVERED_ON)
  private LocalDate deliveredOn;

  public static final String SERIALIZED_NAME_PRODUCT_ITEMS = "productItems";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ITEMS)
  private List<OperationRequestOrderProductItems> productItems = null;


  public OperationRequestOrderOrderItems shipmentAddress(BusinessAddress shipmentAddress) {
    
    this.shipmentAddress = shipmentAddress;
    return this;
  }

   /**
   * Get shipmentAddress
   * @return shipmentAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessAddress getShipmentAddress() {
    return shipmentAddress;
  }


  public void setShipmentAddress(BusinessAddress shipmentAddress) {
    this.shipmentAddress = shipmentAddress;
  }


  public OperationRequestOrderOrderItems shipmentContact(BusinessPerson shipmentContact) {
    
    this.shipmentContact = shipmentContact;
    return this;
  }

   /**
   * Get shipmentContact
   * @return shipmentContact
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessPerson getShipmentContact() {
    return shipmentContact;
  }


  public void setShipmentContact(BusinessPerson shipmentContact) {
    this.shipmentContact = shipmentContact;
  }


  public OperationRequestOrderOrderItems deliveredOn(LocalDate deliveredOn) {
    
    this.deliveredOn = deliveredOn;
    return this;
  }

   /**
   * Order delivery date
   * @return deliveredOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Thu Apr 28 02:00:00 CEST 2022", value = "Order delivery date")

  public LocalDate getDeliveredOn() {
    return deliveredOn;
  }


  public void setDeliveredOn(LocalDate deliveredOn) {
    this.deliveredOn = deliveredOn;
  }


  public OperationRequestOrderOrderItems productItems(List<OperationRequestOrderProductItems> productItems) {
    
    this.productItems = productItems;
    return this;
  }

  public OperationRequestOrderOrderItems addProductItemsItem(OperationRequestOrderProductItems productItemsItem) {
    if (this.productItems == null) {
      this.productItems = new ArrayList<OperationRequestOrderProductItems>();
    }
    this.productItems.add(productItemsItem);
    return this;
  }

   /**
   * Get productItems
   * @return productItems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<OperationRequestOrderProductItems> getProductItems() {
    return productItems;
  }


  public void setProductItems(List<OperationRequestOrderProductItems> productItems) {
    this.productItems = productItems;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationRequestOrderOrderItems operationRequestOrderOrderItems = (OperationRequestOrderOrderItems) o;
    return Objects.equals(this.shipmentAddress, operationRequestOrderOrderItems.shipmentAddress) &&
        Objects.equals(this.shipmentContact, operationRequestOrderOrderItems.shipmentContact) &&
        Objects.equals(this.deliveredOn, operationRequestOrderOrderItems.deliveredOn) &&
        Objects.equals(this.productItems, operationRequestOrderOrderItems.productItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipmentAddress, shipmentContact, deliveredOn, productItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationRequestOrderOrderItems {\n");
    sb.append("    shipmentAddress: ").append(toIndentedString(shipmentAddress)).append("\n");
    sb.append("    shipmentContact: ").append(toIndentedString(shipmentContact)).append("\n");
    sb.append("    deliveredOn: ").append(toIndentedString(deliveredOn)).append("\n");
    sb.append("    productItems: ").append(toIndentedString(productItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

