/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * OperationRequestOrderProductItems
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:16:14.922776+02:00[Europe/Paris]")
public class OperationRequestOrderProductItems {
  public static final String SERIALIZED_NAME_PRODUCT_REF = "productRef";
  @SerializedName(SERIALIZED_NAME_PRODUCT_REF)
  private String productRef;

  public static final String SERIALIZED_NAME_PRODUCT_LABEL = "productLabel";
  @SerializedName(SERIALIZED_NAME_PRODUCT_LABEL)
  private String productLabel;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private Integer quantity;

  public static final String SERIALIZED_NAME_PACKAGING = "packaging";
  @SerializedName(SERIALIZED_NAME_PACKAGING)
  private String packaging;

  public static final String SERIALIZED_NAME_UNIT_PRICE = "unitPrice";
  @SerializedName(SERIALIZED_NAME_UNIT_PRICE)
  private BigDecimal unitPrice;

  public static final String SERIALIZED_NAME_VAT_RATE = "vatRate";
  @SerializedName(SERIALIZED_NAME_VAT_RATE)
  private BigDecimal vatRate;

  public static final String SERIALIZED_NAME_AMOUNT_WITHOUT_TAX = "amountWithoutTax";
  @SerializedName(SERIALIZED_NAME_AMOUNT_WITHOUT_TAX)
  private BigDecimal amountWithoutTax;

  public static final String SERIALIZED_NAME_AMOUNT_TAX = "amountTax";
  @SerializedName(SERIALIZED_NAME_AMOUNT_TAX)
  private BigDecimal amountTax;

  public static final String SERIALIZED_NAME_AMOUNT_WITH_TAX = "amountWithTax";
  @SerializedName(SERIALIZED_NAME_AMOUNT_WITH_TAX)
  private BigDecimal amountWithTax;

  public static final String SERIALIZED_NAME_AMOUNT_ECO_PARTICIPATION = "amountEcoParticipation";
  @SerializedName(SERIALIZED_NAME_AMOUNT_ECO_PARTICIPATION)
  private BigDecimal amountEcoParticipation;


  public OperationRequestOrderProductItems productRef(String productRef) {
    
    this.productRef = productRef;
    return this;
  }

   /**
   * Get productRef
   * @return productRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProductRef() {
    return productRef;
  }


  public void setProductRef(String productRef) {
    this.productRef = productRef;
  }


  public OperationRequestOrderProductItems productLabel(String productLabel) {
    
    this.productLabel = productLabel;
    return this;
  }

   /**
   * Get productLabel
   * @return productLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProductLabel() {
    return productLabel;
  }


  public void setProductLabel(String productLabel) {
    this.productLabel = productLabel;
  }


  public OperationRequestOrderProductItems quantity(Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getQuantity() {
    return quantity;
  }


  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  public OperationRequestOrderProductItems packaging(String packaging) {
    
    this.packaging = packaging;
    return this;
  }

   /**
   * Get packaging
   * @return packaging
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPackaging() {
    return packaging;
  }


  public void setPackaging(String packaging) {
    this.packaging = packaging;
  }


  public OperationRequestOrderProductItems unitPrice(BigDecimal unitPrice) {
    
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getUnitPrice() {
    return unitPrice;
  }


  public void setUnitPrice(BigDecimal unitPrice) {
    this.unitPrice = unitPrice;
  }


  public OperationRequestOrderProductItems vatRate(BigDecimal vatRate) {
    
    this.vatRate = vatRate;
    return this;
  }

   /**
   * Get vatRate
   * @return vatRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getVatRate() {
    return vatRate;
  }


  public void setVatRate(BigDecimal vatRate) {
    this.vatRate = vatRate;
  }


  public OperationRequestOrderProductItems amountWithoutTax(BigDecimal amountWithoutTax) {
    
    this.amountWithoutTax = amountWithoutTax;
    return this;
  }

   /**
   * Get amountWithoutTax
   * @return amountWithoutTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getAmountWithoutTax() {
    return amountWithoutTax;
  }


  public void setAmountWithoutTax(BigDecimal amountWithoutTax) {
    this.amountWithoutTax = amountWithoutTax;
  }


  public OperationRequestOrderProductItems amountTax(BigDecimal amountTax) {
    
    this.amountTax = amountTax;
    return this;
  }

   /**
   * Get amountTax
   * @return amountTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getAmountTax() {
    return amountTax;
  }


  public void setAmountTax(BigDecimal amountTax) {
    this.amountTax = amountTax;
  }


  public OperationRequestOrderProductItems amountWithTax(BigDecimal amountWithTax) {
    
    this.amountWithTax = amountWithTax;
    return this;
  }

   /**
   * Get amountWithTax
   * @return amountWithTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getAmountWithTax() {
    return amountWithTax;
  }


  public void setAmountWithTax(BigDecimal amountWithTax) {
    this.amountWithTax = amountWithTax;
  }


  public OperationRequestOrderProductItems amountEcoParticipation(BigDecimal amountEcoParticipation) {
    
    this.amountEcoParticipation = amountEcoParticipation;
    return this;
  }

   /**
   * Necessary for e-Invoicing
   * @return amountEcoParticipation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Necessary for e-Invoicing")

  public BigDecimal getAmountEcoParticipation() {
    return amountEcoParticipation;
  }


  public void setAmountEcoParticipation(BigDecimal amountEcoParticipation) {
    this.amountEcoParticipation = amountEcoParticipation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationRequestOrderProductItems operationRequestOrderProductItems = (OperationRequestOrderProductItems) o;
    return Objects.equals(this.productRef, operationRequestOrderProductItems.productRef) &&
        Objects.equals(this.productLabel, operationRequestOrderProductItems.productLabel) &&
        Objects.equals(this.quantity, operationRequestOrderProductItems.quantity) &&
        Objects.equals(this.packaging, operationRequestOrderProductItems.packaging) &&
        Objects.equals(this.unitPrice, operationRequestOrderProductItems.unitPrice) &&
        Objects.equals(this.vatRate, operationRequestOrderProductItems.vatRate) &&
        Objects.equals(this.amountWithoutTax, operationRequestOrderProductItems.amountWithoutTax) &&
        Objects.equals(this.amountTax, operationRequestOrderProductItems.amountTax) &&
        Objects.equals(this.amountWithTax, operationRequestOrderProductItems.amountWithTax) &&
        Objects.equals(this.amountEcoParticipation, operationRequestOrderProductItems.amountEcoParticipation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productRef, productLabel, quantity, packaging, unitPrice, vatRate, amountWithoutTax, amountTax, amountWithTax, amountEcoParticipation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationRequestOrderProductItems {\n");
    sb.append("    productRef: ").append(toIndentedString(productRef)).append("\n");
    sb.append("    productLabel: ").append(toIndentedString(productLabel)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    packaging: ").append(toIndentedString(packaging)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    vatRate: ").append(toIndentedString(vatRate)).append("\n");
    sb.append("    amountWithoutTax: ").append(toIndentedString(amountWithoutTax)).append("\n");
    sb.append("    amountTax: ").append(toIndentedString(amountTax)).append("\n");
    sb.append("    amountWithTax: ").append(toIndentedString(amountWithTax)).append("\n");
    sb.append("    amountEcoParticipation: ").append(toIndentedString(amountEcoParticipation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

