/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * OperationResponseAllOfInvoice
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-16T16:16:14.922776+02:00[Europe/Paris]")
public class OperationResponseAllOfInvoice {
  public static final String SERIALIZED_NAME_INVOICE_REF = "invoiceRef";
  @SerializedName(SERIALIZED_NAME_INVOICE_REF)
  private String invoiceRef;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private LocalDate createdAt;


  public OperationResponseAllOfInvoice invoiceRef(String invoiceRef) {
    
    this.invoiceRef = invoiceRef;
    return this;
  }

   /**
   * Get invoiceRef
   * @return invoiceRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInvoiceRef() {
    return invoiceRef;
  }


  public void setInvoiceRef(String invoiceRef) {
    this.invoiceRef = invoiceRef;
  }


  public OperationResponseAllOfInvoice createdAt(LocalDate createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(LocalDate createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationResponseAllOfInvoice operationResponseAllOfInvoice = (OperationResponseAllOfInvoice) o;
    return Objects.equals(this.invoiceRef, operationResponseAllOfInvoice.invoiceRef) &&
        Objects.equals(this.createdAt, operationResponseAllOfInvoice.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invoiceRef, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationResponseAllOfInvoice {\n");
    sb.append("    invoiceRef: ").append(toIndentedString(invoiceRef)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

